import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import { Providers } from './providers';
import { MainHeader } from '@/components/headers/MainHeader';
import MainFooter from '@/components/footers/MainFooter';
import './assets/main.scss';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Next ts shop',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning>
      <body className={inter.className}>
        <Providers>
          <MainHeader />
          <main style={{ flexGrow: 1 }}>{children}</main>
          <MainFooter />
        </Providers>
      </body>
    </html>
  );
}
